website_port: 3000
website_deploy_directory: c:\iisexpress\website
website_port_load_balanced_1: 4000
website_deploy_directory_load_balanced_1: c:\iisexpress\website_4000
website_port_load_balanced_2: 5000
website_deploy_directory_load_balanced_2: c:\iisexpress\website_5000
solution_name: BorrowedGames
mvc_project: BorrowedGames 
test_project: BorrowedGames.Tests
test_runner: ./packages/nspec.0.9.62/tools/NSpecRunner.exe
iis_express: C:\Program Files (x86)\IIS Express
database_name: BorrowedGames
database_server: (local)
